<h1>Poweradmin</h1>
<div class="content">
    <h2>Log in</h2>
    <form method="post" action="index.php">
        <table border="0">
            <tr>
                <td class="n" width="100">Username:</td>
                <td class="n"><input type="text" class="input" name="username" id="username"></td>
            </tr>
            <tr>
                <td class="n">Password:</td>
                <td class="n"><input type="password" class="input" name="password"></td>
            </tr>
            <tr>
                <td class="n">&nbsp;</td>
                <td class="n">
                    <input type="submit" name="authenticate" class="button" value=" Go ">
                </td>
            </tr>
        </table>
    </form>
    <script type="text/javascript">
        <!--
        document.getElementById('username').focus();
        //-->
    </script>
</div> <!-- /content -->
